version: "3"

tasks:
  docker:
    cmds:
      - docker compose up --build
  docker-watch:
    cmds:
      - docker compose watch
  dev:
    cmds:
      - cmd: ./bin/air/air_1.49.0_{{OS}}_{{ARCH}}
        platforms: [linux, darwin]
      - cmd: ./bin/air/air_1.49.0_{{OS}}_{{ARCH}}.exe
        platforms: [windows]
  tailwindcss:
    cmds:
      - cmd: ./bin/tailwindcss/tailwindcss_{{OS}}_{{ARCH}} -o ./assets/style.css --minify
        platforms: [linux, darwin]
      - cmd: ./bin/tailwindcss/tailwindcss_{{OS}}_{{ARCH}}.exe -o ./assets/style.css --minify
        platforms: [windows]
  templ:
    cmds:
      - cmd: ./bin/templ/templ_{{OS}}_{{ARCH}} generate
        platforms: [linux, darwin]
      - cmd: ./bin/templ/templ_{{OS}}_{{ARCH}}.exe generate
        platforms: [windows]
